source 'https://rubygems.org'
ruby "3.0.3"
gem "sinatra"
gem "sinatra-contrib"
gem "pry-byebug"
gem "better_errors"
gem "binding_of_caller"
gem "json"
gem 'rake'
gem 'rack'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
