development:
  adapter: postgresql
  encoding: unicode
  database: jdrperso
  pool: 2


production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  host: localhost
  pool: 5
  timeout: 5000
